PublicBodyCategories.add(:en, [
    "Central Institutions",
        [ "prime_minister_office", "Prime minister office", "a prime minister office" ], 
        [ "ministries", "Ministries", "a ministry" ], 
        [ "assembly", "Assembly", "an assembly" ], 
        [ "president", "President", "a president" ],
    "Local Institutions",
        [ "municipal_assemblies", "Municipal assemblies", "a municipal assembly" ], 
    "Independent Institutions",
        [ "independent_institutions", "Independent Institutions", "an independent institution" ],
    "Public Enterprises",
        [ "water_companies", "Water companies", "a water company" ], 
        [ "waste_disposal_companies", "Waste disposal companies", "a waste disposal company" ],
        [ "public_enterprises", "Public Enterprises", "a public enterprise" ],
    "Courts",
        [ "municipal_courts", "Municipal courts", "Municipal courts" ],
        [ "district_courts", "District courts", "a district court" ],
        [ "public_attorneys", "Public attorneys", "a public attorney" ],
        [ "other_courts", "Other courts", "other courts" ],
	"Education",
		[ "universities", "Universities", "an university" ],
	"Health",
		[ "hostipals", "Hospitals", "a hospital" ],		
    "Miscellaneous",
        [ "other", "Miscellaneous", "miscellaneous" ]
])

